version: "2"

run:
  go: "1.25"
  timeout: 5m

linters:
  disable:
    - errcheck
    - staticcheck

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - staticcheck
