version: "2"

run:
  go: "1.25"
  timeout: 5m
  skip-dirs:
    - vendor

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - staticcheck
        - unused
        - govet
        - ineffassign
  exclude:
    - "could not import"
    - typecheck
